# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: "3.8"
services:
  app:
    container_name: chaca-backend-prod
    build:
      context: ./
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
