import { SubOption } from "../../../modules/schema-options/interfaces/options.interface";
import { schemas } from "chaca";

export const AnimalOptions: SubOption[] = [
  {
    name: "Bear",
    exampleValue: schemas.animal.bear().getValue(),
    getValue: () => schemas.animal.bear().getValue(),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de oso" },
  },
  {
    name: "Bird",
    exampleValue: schemas.animal.bird().getValue(),
    getValue: (a) => schemas.animal.bird().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de ave" },
  },
  {
    name: "Cat",
    exampleValue: schemas.animal.cat().getValue(),
    getValue: (a) => schemas.animal.cat().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de gato" },
  },
  {
    name: "Cetacean",
    exampleValue: schemas.animal.cetacean().getValue(),
    getValue: (a) => schemas.animal.cetacean().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de cetáceo" },
  },
  {
    name: "Cow",
    exampleValue: schemas.animal.cow().getValue(),
    getValue: (a) => schemas.animal.cow().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de vaca" },
  },
  {
    name: "Crocodilia",
    exampleValue: schemas.animal.crocodilia().getValue(),
    getValue: (a) => schemas.animal.crocodilia().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de cocodrilo" },
  },
  {
    name: "Dog",
    exampleValue: schemas.animal.dog().getValue(),
    getValue: (a) => schemas.animal.dog().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de perro" },
  },
  {
    name: "Horse",
    exampleValue: schemas.animal.horse().getValue(),
    getValue: (a) => schemas.animal.horse().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de caballo" },
  },
  {
    name: "Insect",
    exampleValue: schemas.animal.insect().getValue(),
    getValue: (a) => schemas.animal.insect().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de insecto" },
  },
  {
    name: "Lion",
    exampleValue: schemas.animal.lion().getValue(),
    getValue: (a) => schemas.animal.lion().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de león" },
  },
  {
    name: "Rabbit",
    exampleValue: schemas.animal.rabbit().getValue(),
    getValue: (a) => schemas.animal.rabbit().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de conejo" },
  },
  {
    name: "Snake",
    exampleValue: schemas.animal.snake().getValue(),
    getValue: (a) => schemas.animal.snake().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de serpiente" },
  },
  {
    name: "Animal Type",
    exampleValue: schemas.animal.animalType().getValue(),
    getValue: (a) => schemas.animal.animalType().getValue(a),
    arguments: [],
    description: { en: "", es: "Devuelve el nombre de un tipo de animal" },
  },
];
