import { Schema } from "../interfaces/options";
import { AddressOptions } from "./AddressOptions";
import { AnimalOptions } from "./AnimalOptions";
import { DataTypeOptions } from "./DataTypeOptions";
import { DateOptions } from "./DateOptions";
import { FinanceOptions } from "./FinanceOptions";
import { IdOptions } from "./IdOptions";
import { ImageOptions } from "./ImageOptions";
import { InternetOptions } from "./InternetOptions";
import { LoremOptions } from "./LoremOptions";
import { PersonOptions } from "./PersonOptions";
import { PhoneOptions } from "./PhoneOptions";
import { SystemOptions } from "./SystemOptions";
import { VehicleOptions } from "./VehicleOptions";
import { VideoOptions } from "./VideoOptions";
import { WordOptions } from "./WordOptions";

export const SCHEMAS: Array<Schema> = [
  { name: "Address", options: AddressOptions },
  { name: "Animal", options: AnimalOptions },
  { name: "DataType", options: DataTypeOptions },
  { name: "Date", options: DateOptions },
  { name: "Finance", options: FinanceOptions },
  { name: "Id", options: IdOptions },
  { name: "Image", options: ImageOptions },
  { name: "Internet", options: InternetOptions },
  { name: "Lorem", options: LoremOptions },
  { name: "Person", options: PersonOptions },
  { name: "Phone", options: PhoneOptions },
  { name: "System", options: SystemOptions },
  { name: "Vehicle", options: VehicleOptions },
  { name: "Video", options: VideoOptions },
  { name: "Word", options: WordOptions },
];
