export enum NO_USER_LIMITS {
  LIMIT_DATASETS = 3,
  LIMIT_DOCUMENTS = 1000,
}

export enum NORMAL_USER_LIMITS {
  LIMIT_DATASETS = 5,
  LIMIT_DOCUMENTS = 1500,
}

export enum SUPER_USER_LIMITS {
  LIMIT_DATASETS = 10,
  LIMIT_DOCUMENTS = 3000,
}
